---
title: "Visualization"
author: "Charles Alba"
date: "2022-12-24"
output: pdf_document
---

loading libraries
```{r setup, include=FALSE}
library(data.table)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tidyverse)
```

Reading files, cleaning the columns and plotting the figures
```{r}
# reading the data
data<-read.csv("sentimental_count.csv")
colnames(data)[which(names(data) == "X")] <- "Date"
data<-melt(data, id = c("Date")) 
data$variable<-as.character(data$variable)

covid<-read.csv("COVID_cases.csv")

# wrangling the data to prepare for visualization

covid$Date<-format(as.Date(covid$date), format="%m-%d")
covid$covid_cases_per_10000<-(covid$covid_cases_per_10000)
covid$COVID<-"COVID cases per 10,000"
data[data == 'Tweets'] <- 'Tweets Associated with \'orphans\''
data[data == 'anger'] <- 'Tweets with Anger'
data[data == 'disgust'] <- 'Tweets with Disgust'
data[data == 'fear'] <- 'Tweets with Fear'
data[data == 'sadness'] <- 'Tweets with Sadness'
data[data == 'sentiment_NEG'] <- 'Negative Tweets'





colnames(data)[which(names(data) == "variable")] <- "Tweet_type"
colnames(data)[which(names(data) == "value")] <- "Tweet_count"
data$Tweet_type <- factor(data$Tweet_type, levels = c('Tweets Associated with \'orphans\'','Negative Tweets','Tweets with Anger','Tweets with Disgust','Tweets with Fear','Tweets with Sadness'))
data$Tweet_count<-as.numeric(data$Tweet_count)
data$Date<-format(as.Date(data$Date), format="%m-%d")
COVID<-subset(covid,select=c(Date,covid_cases_per_10000))
df<-merge(data,COVID,by.x="Date",by.y="Date",all.x=T)

df<-df %>% pivot_longer(-c(Date,Tweet_type))

# plotting the figure comparing each to the COVID incidence rate
graph<-ggplot(aes(x=Date, y=value, color= name,group=name),data=df)+geom_line()+facet_wrap(~Tweet_type,ncol=2,scales = "free_y")+ylab("Count")+ theme_bw()+theme(axis.text.x = element_text(angle = 90,vjust=0.5, hjust=1))+scale_color_manual(name="Count Type",labels=c('New COVID cases per 10,000', 'Tweet Counts'), values = c("red", "blue"))
graph
  #geom_line(aes(x=Date,y=covid_cases_per_10000,color=COVID,group=COVID),linetype = "dashed",data=covid)+
  #ylab("Tweet counts")+
  #scale_y_continuous(sec.axis = sec_axis(~ .*(1/2), name ="COVID cases per 10000"))+
  #scale_color_discrete(name = expression(underline("Tweet type/sentiment/emotion")))+ theme_bw()+ theme(axis.text.x = element_text(angle = 70, hjust=1), legend.background = element_rect(fill = "white"))+ 
  #scale_colour_manual(breaks=c('Associated with \'orphans\'','Negative','Fear','Anger','Sadness',  'Disgust','Anticipation'), values=c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7"))


```

```{r}
# plotting the figure comparing all Tweet types across time. 
ggplot()+
  geom_line(aes(x=Date,y=Tweet_count, color=Tweet_type,group=Tweet_type),data=data)+scale_color_discrete(name = expression(underline("Tweet type/sentiment/emotion")))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 70, hjust=1),legend.position = c(0.3,.8 ), 
        legend.background=element_rect(fill ="white"),
        legend.text=element_text(size=8),
        legend.title=element_text(size=9))+
  ylim(0,30)+ylab("Tweet Count")+
  guides(color=guide_legend(ncol=2),
         panel.border = element_blank(), 
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank())
```


